spring:
  profiles: 
    active: dev
  boot:
    admin:
      client:
        url:
        - http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include:
        - metrics
        - info
        - health
        - env

---
spring: 
  profiles: dev

---
spring:
  profiles: prod

logging:
  file: logs/app.log
